spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderflowlab
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: order-flow-lab
      auto-offset-reset: earliest

    producer:
      client-id: order-flow-lab-producer

management:
  endpoints:
    web:
      exposure:
        include: health