spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_flow_lab
    username: orderflow
    password: orderflow

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true